### ISSUE TITLE
Permission problems and not complete mongo installation

### ISSUE THREAD

**Issue by digixweb** [zakhttp/Mongostead7#8]
I ran into several permission issues:

Line 28/29:

sudo echo  "extension = mongodb.so" >> /etc/php/7.0/cli/php.ini;
sudo echo  "extension = mongodb.so" >> /etc/php/7.0/fpm/php.ini;

needed to be adjusted to:

sudo sh -c "echo 'extension = mongodb.so' >> /etc/php/7.0/cli/php.ini";
sudo sh -c "echo 'extension = mongodb.so' >> /etc/php/7.0/fpm/php.ini";

I also needed to manually add the mongodb.service file.

Finally I had to install mongo manually after all of this.
sudo apt-get install -y mongodb-org

And now it is running.

**Comment by zakhttp** [comment]
What errors did you get @digixweb ?
